export const IPC_CHANNELS = {
  appRuntimeConfig: "agent-hub:app:runtime-config",
  projectsList: "agent-hub:projects:list",
  projectsOpen: "agent-hub:projects:open",
  projectsSelectDirectory: "agent-hub:projects:select-directory",
  runsList: "agent-hub:runs:list",
  runsGet: "agent-hub:runs:get",
  runsCreate: "agent-hub:runs:create",
  runsCancel: "agent-hub:runs:cancel",
  runsSubscribe: "agent-hub:runs:subscribe",
  runsUnsubscribe: "agent-hub:runs:unsubscribe",
  threadsList: "agent-hub:threads:list",
  threadsGet: "agent-hub:threads:get",
  threadsCreate: "agent-hub:threads:create",
  threadsUpdate: "agent-hub:threads:update",
  threadsSendMessage: "agent-hub:threads:send-message",
  reviewSummary: "agent-hub:review:summary",
  reviewContext: "agent-hub:review:context",
  reviewArtifacts: "agent-hub:review:artifacts",
  reviewDiff: "agent-hub:review:diff",
  reviewRisk: "agent-hub:review:risk",
  reviewVerification: "agent-hub:review:verification",
  reviewLogs: "agent-hub:review:logs",
  reviewHandoff: "agent-hub:review:handoff",
  reviewHandoffOpenWorktree: "agent-hub:review:handoff:open-worktree",
  reviewHandoffCopyValue: "agent-hub:review:handoff:copy-value",
  reviewAccept: "agent-hub:review:accept",
  reviewReject: "agent-hub:review:reject",
  reviewRefresh: "agent-hub:review:refresh",
  lifecycleGet: "agent-hub:lifecycle:get",
  lifecycleMarkKeep: "agent-hub:lifecycle:mark-keep",
  lifecycleCleanupWorktree: "agent-hub:lifecycle:cleanup-worktree",
  lifecyclePreviewApply: "agent-hub:lifecycle:preview-apply",
  lifecycleConfirmApply: "agent-hub:lifecycle:confirm-apply",
  comparisonListCandidates: "agent-hub:comparison:list-candidates",
  comparisonListForRun: "agent-hub:comparison:list-for-run",
  comparisonCreate: "agent-hub:comparison:create",
  memoryListProposals: "agent-hub:memory:list-proposals",
  memoryGenerateProposals: "agent-hub:memory:generate-proposals",
  memoryApprove: "agent-hub:memory:approve",
  memoryIgnore: "agent-hub:memory:ignore",
  knowledgeWorkspace: "agent-hub:knowledge:workspace",
  teamWorkspace: "agent-hub:team:workspace",
  teamSaveRole: "agent-hub:team:save-role",
  settingsGetVerification: "agent-hub:settings:get-verification",
  settingsSaveVerification: "agent-hub:settings:save-verification"
} as const;

export function runEventChannel(runId: string): string {
  return `agent-hub:runs:event:${runId}`;
}
